/* Generated By:JavaCC: Do not edit this line. dbGrammarConstants.java */
package Analisis.XML.DB;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface dbGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_TABLA_IZQ = 1;
  /** RegularExpression Id. */
  int T_PATH_IZQ = 2;
  /** RegularExpression Id. */
  int T_OBJECT_IZQ = 3;
  /** RegularExpression Id. */
  int T_PROCEDURE_IZQ = 4;
  /** RegularExpression Id. */
  int T_FUNCION_IZQ = 5;
  /** RegularExpression Id. */
  int T_NOMBRE_IZQ = 6;
  /** RegularExpression Id. */
  int T_ROWS_IZQ = 7;
  /** RegularExpression Id. */
  int T_COMPLEMENTO_IZQ = 8;
  /** RegularExpression Id. */
  int T_CAMPO_IZQ = 9;
  /** RegularExpression Id. */
  int T_TABLA_DER = 10;
  /** RegularExpression Id. */
  int T_PATH_DER = 11;
  /** RegularExpression Id. */
  int T_OBJECT_DER = 12;
  /** RegularExpression Id. */
  int T_PROCEDURE_DER = 13;
  /** RegularExpression Id. */
  int T_FUNCION_DER = 14;
  /** RegularExpression Id. */
  int T_NOMBRE_DER = 15;
  /** RegularExpression Id. */
  int T_ROWS_DER = 16;
  /** RegularExpression Id. */
  int T_COMPLEMENTO_DER = 17;
  /** RegularExpression Id. */
  int T_CAMPO_DER = 18;
  /** RegularExpression Id. */
  int T_FA = 19;
  /** RegularExpression Id. */
  int T_FC = 20;
  /** RegularExpression Id. */
  int T_NULO = 21;
  /** RegularExpression Id. */
  int T_NO_NULO = 22;
  /** RegularExpression Id. */
  int T_AUTOINCREMETABLE = 23;
  /** RegularExpression Id. */
  int T_LLAVE_PRIMARIA = 24;
  /** RegularExpression Id. */
  int T_FORANEA_IZQ = 25;
  /** RegularExpression Id. */
  int T_FORANEA_DER = 26;
  /** RegularExpression Id. */
  int T_TEXT_IZQ = 27;
  /** RegularExpression Id. */
  int T_INTEGER_IZQ = 28;
  /** RegularExpression Id. */
  int T_DOUBLE_IZQ = 29;
  /** RegularExpression Id. */
  int T_BOOL_IZQ = 30;
  /** RegularExpression Id. */
  int T_DATE_IZQ = 31;
  /** RegularExpression Id. */
  int T_DATETIME_IZQ = 32;
  /** RegularExpression Id. */
  int T_TEXT_DER = 33;
  /** RegularExpression Id. */
  int T_INTEGER_DER = 34;
  /** RegularExpression Id. */
  int T_DOUBLE_DER = 35;
  /** RegularExpression Id. */
  int T_BOOL_DER = 36;
  /** RegularExpression Id. */
  int T_DATE_DER = 37;
  /** RegularExpression Id. */
  int T_DATETIME_DER = 38;
  /** RegularExpression Id. */
  int CADENA = 39;
  /** RegularExpression Id. */
  int ID_IZQ = 40;
  /** RegularExpression Id. */
  int ID_DER = 41;
  /** RegularExpression Id. */
  int ENTERO = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<T_TABLA_IZQ>",
    "<T_PATH_IZQ>",
    "<T_OBJECT_IZQ>",
    "<T_PROCEDURE_IZQ>",
    "<T_FUNCION_IZQ>",
    "<T_NOMBRE_IZQ>",
    "<T_ROWS_IZQ>",
    "<T_COMPLEMENTO_IZQ>",
    "<T_CAMPO_IZQ>",
    "<T_TABLA_DER>",
    "<T_PATH_DER>",
    "<T_OBJECT_DER>",
    "<T_PROCEDURE_DER>",
    "<T_FUNCION_DER>",
    "<T_NOMBRE_DER>",
    "<T_ROWS_DER>",
    "<T_COMPLEMENTO_DER>",
    "<T_CAMPO_DER>",
    "\"<\"",
    "\">\"",
    "\"nulo\"",
    "\"no nulo\"",
    "\"autoincrementable\"",
    "\"llave_primaria\"",
    "<T_FORANEA_IZQ>",
    "<T_FORANEA_DER>",
    "<T_TEXT_IZQ>",
    "<T_INTEGER_IZQ>",
    "<T_DOUBLE_IZQ>",
    "<T_BOOL_IZQ>",
    "<T_DATE_IZQ>",
    "<T_DATETIME_IZQ>",
    "<T_TEXT_DER>",
    "<T_INTEGER_DER>",
    "<T_DOUBLE_DER>",
    "<T_BOOL_DER>",
    "<T_DATE_DER>",
    "<T_DATETIME_DER>",
    "<CADENA>",
    "<ID_IZQ>",
    "<ID_DER>",
    "<ENTERO>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
