/* Generated By:JavaCC: Do not edit this line. AnalisisConstants.java */
package Analisis;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalisisConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAS = 1;
  /** RegularExpression Id. */
  int MENOS = 2;
  /** RegularExpression Id. */
  int POR = 3;
  /** RegularExpression Id. */
  int DIVISION = 4;
  /** RegularExpression Id. */
  int POTENCIA = 5;
  /** RegularExpression Id. */
  int AUMENTO = 6;
  /** RegularExpression Id. */
  int DECREMENTO = 7;
  /** RegularExpression Id. */
  int PAR_IZQ = 8;
  /** RegularExpression Id. */
  int PAR_DER = 9;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 10;
  /** RegularExpression Id. */
  int LLAVE_DER = 11;
  /** RegularExpression Id. */
  int COR_IZQ = 12;
  /** RegularExpression Id. */
  int COR_DER = 13;
  /** RegularExpression Id. */
  int PCOMA = 14;
  /** RegularExpression Id. */
  int COMA = 15;
  /** RegularExpression Id. */
  int DOSP = 16;
  /** RegularExpression Id. */
  int IGUAL = 17;
  /** RegularExpression Id. */
  int ARROBA = 18;
  /** RegularExpression Id. */
  int PUNTO = 19;
  /** RegularExpression Id. */
  int IGUALACION = 20;
  /** RegularExpression Id. */
  int DIFERENCIACION = 21;
  /** RegularExpression Id. */
  int MENOR = 22;
  /** RegularExpression Id. */
  int MAYOR = 23;
  /** RegularExpression Id. */
  int MENORIGUAL = 24;
  /** RegularExpression Id. */
  int MAYORIGUAL = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int NOT = 28;
  /** RegularExpression Id. */
  int T_TEXT = 29;
  /** RegularExpression Id. */
  int T_INTEGER = 30;
  /** RegularExpression Id. */
  int T_DOUBLE = 31;
  /** RegularExpression Id. */
  int T_BOOL = 32;
  /** RegularExpression Id. */
  int T_DATE = 33;
  /** RegularExpression Id. */
  int T_DATETIME = 34;
  /** RegularExpression Id. */
  int T_CREAR = 35;
  /** RegularExpression Id. */
  int T_BASE_DATOS = 36;
  /** RegularExpression Id. */
  int T_TABLA = 37;
  /** RegularExpression Id. */
  int T_NULO = 38;
  /** RegularExpression Id. */
  int T_NO_NULO = 39;
  /** RegularExpression Id. */
  int T_AUTOINCREMETABLE = 40;
  /** RegularExpression Id. */
  int T_LLAVE_PRIMARIA = 41;
  /** RegularExpression Id. */
  int T_LLAVE_FORANEA = 42;
  /** RegularExpression Id. */
  int T_OBJETO = 43;
  /** RegularExpression Id. */
  int T_PROCEDIMIENTO = 44;
  /** RegularExpression Id. */
  int T_FUNCION = 45;
  /** RegularExpression Id. */
  int T_RETORNO = 46;
  /** RegularExpression Id. */
  int T_USUARIO = 47;
  /** RegularExpression Id. */
  int T_COLOCAR = 48;
  /** RegularExpression Id. */
  int T_PASSWORD = 49;
  /** RegularExpression Id. */
  int T_USAR = 50;
  /** RegularExpression Id. */
  int T_ALTERAR = 51;
  /** RegularExpression Id. */
  int T_AGREGAR = 52;
  /** RegularExpression Id. */
  int T_QUITAR = 53;
  /** RegularExpression Id. */
  int T_CAMBIAR = 54;
  /** RegularExpression Id. */
  int T_ELIMINAR = 55;
  /** RegularExpression Id. */
  int T_INSERTAR = 56;
  /** RegularExpression Id. */
  int T_VALORES = 57;
  /** RegularExpression Id. */
  int T_ACTUALIZAR = 58;
  /** RegularExpression Id. */
  int T_DONDE = 59;
  /** RegularExpression Id. */
  int T_BORRAR = 60;
  /** RegularExpression Id. */
  int T_SELECCIONAR = 61;
  /** RegularExpression Id. */
  int T_DE = 62;
  /** RegularExpression Id. */
  int T_ORDENAR = 63;
  /** RegularExpression Id. */
  int T_ASC = 64;
  /** RegularExpression Id. */
  int T_DESC = 65;
  /** RegularExpression Id. */
  int T_OTORGAR = 66;
  /** RegularExpression Id. */
  int T_DENEGAR = 67;
  /** RegularExpression Id. */
  int T_DECLARAR = 68;
  /** RegularExpression Id. */
  int T_SI = 69;
  /** RegularExpression Id. */
  int T_SINO = 70;
  /** RegularExpression Id. */
  int T_SELECCIONA = 71;
  /** RegularExpression Id. */
  int T_CASO = 72;
  /** RegularExpression Id. */
  int T_DEFECTO = 73;
  /** RegularExpression Id. */
  int T_PARA = 74;
  /** RegularExpression Id. */
  int T_MIENTRAS = 75;
  /** RegularExpression Id. */
  int T_DETENER = 76;
  /** RegularExpression Id. */
  int T_IMPRIMIR = 77;
  /** RegularExpression Id. */
  int T_FECHA = 78;
  /** RegularExpression Id. */
  int T_FECHA_HORA = 79;
  /** RegularExpression Id. */
  int T_CONTAR = 80;
  /** RegularExpression Id. */
  int T_BACKUP_USQL = 81;
  /** RegularExpression Id. */
  int T_BACKUP_COMPLETO = 82;
  /** RegularExpression Id. */
  int T_RESTAURAR_USQL = 83;
  /** RegularExpression Id. */
  int T_RESTAURAR_COMPLETO = 84;
  /** RegularExpression Id. */
  int CADENA = 85;
  /** RegularExpression Id. */
  int ENTERO = 86;
  /** RegularExpression Id. */
  int NUMERO = 87;
  /** RegularExpression Id. */
  int DECIMAL = 88;
  /** RegularExpression Id. */
  int ID = 89;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 94;
  /** RegularExpression Id. */
  int COMENTARIO_MULTI = 95;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"++\"",
    "\"--\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"=\"",
    "\"@\"",
    "\".\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"text\"",
    "\"integer\"",
    "\"double\"",
    "\"bool\"",
    "\"date\"",
    "\"datetime\"",
    "\"crear\"",
    "\"base_datos\"",
    "\"tabla\"",
    "\"nulo\"",
    "\"no nulo\"",
    "\"autoincrementable\"",
    "\"llave_primaria\"",
    "\"llave_foranea\"",
    "\"objeto\"",
    "\"procedimiento\"",
    "\"funcion\"",
    "\"retorno\"",
    "\"usuario\"",
    "\"colocar\"",
    "\"password\"",
    "\"usar\"",
    "\"alaterar\"",
    "\"agregar\"",
    "\"quitar\"",
    "\"cambiar\"",
    "\"eliminar\"",
    "\"insertar en\"",
    "\"valores\"",
    "\"actualizar\"",
    "\"donde\"",
    "\"borrar en\"",
    "\"seleccionar\"",
    "\"de\"",
    "\"ordenar por\"",
    "\"asc\"",
    "\"desc\"",
    "\"otorgar permisos\"",
    "\"denegar permisos\"",
    "\"declarar\"",
    "\"si\"",
    "\"sino\"",
    "\"selecciona\"",
    "\"caso\"",
    "\"defecto\"",
    "\"para\"",
    "\"mientras\"",
    "\"detener\"",
    "\"imprimir\"",
    "\"fecha\"",
    "\"fecha_hora\"",
    "\"contar\"",
    "\"backup usqldump\"",
    "\"backup completo\"",
    "\"restaurar usqldump\"",
    "\"restaurar completo\"",
    "<CADENA>",
    "<ENTERO>",
    "<NUMERO>",
    "<DECIMAL>",
    "<ID>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMENTARIO_LINEA>",
    "<COMENTARIO_MULTI>",
  };

}
