/* Generated By:JavaCC: Do not edit this line. usrGrammarConstants.java */
package Analisis.XML.Usuario;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface usrGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_USR_IZQ = 1;
  /** RegularExpression Id. */
  int T_USR_DER = 2;
  /** RegularExpression Id. */
  int T_NOMBRE_IZQ = 3;
  /** RegularExpression Id. */
  int T_NOMBRE_DER = 4;
  /** RegularExpression Id. */
  int T_PASS_IZQ = 5;
  /** RegularExpression Id. */
  int T_PASS_DER = 6;
  /** RegularExpression Id. */
  int T_TIPO_IZQ = 7;
  /** RegularExpression Id. */
  int T_TIPO_DER = 8;
  /** RegularExpression Id. */
  int T_ESTADO_IZQ = 9;
  /** RegularExpression Id. */
  int T_ESTADO_DER = 10;
  /** RegularExpression Id. */
  int T_SESION_IZQ = 11;
  /** RegularExpression Id. */
  int T_SESION_DER = 12;
  /** RegularExpression Id. */
  int T_PERMISOS_IZQ = 13;
  /** RegularExpression Id. */
  int T_PERMISOS_DER = 14;
  /** RegularExpression Id. */
  int T_DB_IZQ = 15;
  /** RegularExpression Id. */
  int T_DB_DER = 16;
  /** RegularExpression Id. */
  int T_FUNC_IZQ = 17;
  /** RegularExpression Id. */
  int T_FUNC_DER = 18;
  /** RegularExpression Id. */
  int T_OBJ_IZQ = 19;
  /** RegularExpression Id. */
  int T_OBJ_DER = 20;
  /** RegularExpression Id. */
  int T_PROC_IZQ = 21;
  /** RegularExpression Id. */
  int T_PROC_DER = 22;
  /** RegularExpression Id. */
  int T_TABLA_IZQ = 23;
  /** RegularExpression Id. */
  int T_TABLA_DER = 24;
  /** RegularExpression Id. */
  int T_UNO = 25;
  /** RegularExpression Id. */
  int T_CERO = 26;
  /** RegularExpression Id. */
  int ID = 27;
  /** RegularExpression Id. */
  int CADENA = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<T_USR_IZQ>",
    "<T_USR_DER>",
    "<T_NOMBRE_IZQ>",
    "<T_NOMBRE_DER>",
    "<T_PASS_IZQ>",
    "<T_PASS_DER>",
    "<T_TIPO_IZQ>",
    "<T_TIPO_DER>",
    "<T_ESTADO_IZQ>",
    "<T_ESTADO_DER>",
    "<T_SESION_IZQ>",
    "<T_SESION_DER>",
    "<T_PERMISOS_IZQ>",
    "<T_PERMISOS_DER>",
    "<T_DB_IZQ>",
    "<T_DB_DER>",
    "<T_FUNC_IZQ>",
    "<T_FUNC_DER>",
    "<T_OBJ_IZQ>",
    "<T_OBJ_DER>",
    "<T_PROC_IZQ>",
    "<T_PROC_DER>",
    "<T_TABLA_IZQ>",
    "<T_TABLA_DER>",
    "\"1\"",
    "\"0\"",
    "<ID>",
    "<CADENA>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
