/* usrGrammarTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. usrGrammarTokenManager.java */
package Analisis.XML.Usuario;
import java.util.ArrayList;
import Funciones.XML.Usr.*;

/** Token Manager. */
@SuppressWarnings("unused")public class usrGrammarTokenManager implements usrGrammarConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 48:
         return jjStopAtPos(0, 26);
      case 49:
         return jjStopAtPos(0, 25);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 212;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (curChar == 60)
                     { jjCheckNAddStates(0, 47); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 2:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 3:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(3, 4); }
                  break;
               case 4:
                  if (curChar == 34 && kind > 28)
                     kind = 28;
                  break;
               case 5:
                  if (curChar == 60)
                     { jjCheckNAddStates(0, 47); }
                  break;
               case 6:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(6, 11); }
                  break;
               case 8:
                  if (curChar == 32)
                     { jjAddStates(48, 49); }
                  break;
               case 9:
                  if (curChar == 62 && kind > 1)
                     kind = 1;
                  break;
               case 12:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(12, 13); }
                  break;
               case 13:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(14, 19); }
                  break;
               case 14:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(14, 19); }
                  break;
               case 16:
                  if (curChar == 32)
                     { jjAddStates(50, 51); }
                  break;
               case 17:
                  if (curChar == 62 && kind > 2)
                     kind = 2;
                  break;
               case 20:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(20, 28); }
                  break;
               case 22:
                  if (curChar == 32)
                     { jjAddStates(52, 53); }
                  break;
               case 23:
                  if (curChar == 62 && kind > 3)
                     kind = 3;
                  break;
               case 29:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(29, 30); }
                  break;
               case 30:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(31, 39); }
                  break;
               case 31:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(31, 39); }
                  break;
               case 33:
                  if (curChar == 32)
                     { jjAddStates(54, 55); }
                  break;
               case 34:
                  if (curChar == 62 && kind > 4)
                     kind = 4;
                  break;
               case 40:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(40, 46); }
                  break;
               case 42:
                  if (curChar == 32)
                     { jjAddStates(56, 57); }
                  break;
               case 43:
                  if (curChar == 62 && kind > 5)
                     kind = 5;
                  break;
               case 47:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(47, 48); }
                  break;
               case 48:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(49, 55); }
                  break;
               case 49:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(49, 55); }
                  break;
               case 51:
                  if (curChar == 32)
                     { jjAddStates(58, 59); }
                  break;
               case 52:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 56:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(56, 62); }
                  break;
               case 58:
                  if (curChar == 32)
                     { jjAddStates(60, 61); }
                  break;
               case 59:
                  if (curChar == 62 && kind > 7)
                     kind = 7;
                  break;
               case 63:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(63, 64); }
                  break;
               case 64:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(65, 71); }
                  break;
               case 65:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(65, 71); }
                  break;
               case 67:
                  if (curChar == 32)
                     { jjAddStates(62, 63); }
                  break;
               case 68:
                  if (curChar == 62 && kind > 8)
                     kind = 8;
                  break;
               case 72:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(72, 80); }
                  break;
               case 74:
                  if (curChar == 32)
                     { jjAddStates(64, 65); }
                  break;
               case 75:
                  if (curChar == 62 && kind > 9)
                     kind = 9;
                  break;
               case 81:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(81, 82); }
                  break;
               case 82:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(83, 91); }
                  break;
               case 83:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(83, 91); }
                  break;
               case 85:
                  if (curChar == 32)
                     { jjAddStates(66, 67); }
                  break;
               case 86:
                  if (curChar == 62 && kind > 10)
                     kind = 10;
                  break;
               case 92:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(92, 100); }
                  break;
               case 94:
                  if (curChar == 32)
                     { jjAddStates(68, 69); }
                  break;
               case 95:
                  if (curChar == 62 && kind > 11)
                     kind = 11;
                  break;
               case 101:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(101, 102); }
                  break;
               case 102:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(103, 111); }
                  break;
               case 103:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(103, 111); }
                  break;
               case 105:
                  if (curChar == 32)
                     { jjAddStates(70, 71); }
                  break;
               case 106:
                  if (curChar == 62 && kind > 12)
                     kind = 12;
                  break;
               case 112:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(112, 122); }
                  break;
               case 114:
                  if (curChar == 32)
                     { jjAddStates(72, 73); }
                  break;
               case 115:
                  if (curChar == 62 && kind > 13)
                     kind = 13;
                  break;
               case 123:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(123, 124); }
                  break;
               case 124:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(125, 135); }
                  break;
               case 125:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(125, 135); }
                  break;
               case 127:
                  if (curChar == 32)
                     { jjAddStates(74, 75); }
                  break;
               case 128:
                  if (curChar == 62 && kind > 14)
                     kind = 14;
                  break;
               case 136:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(136, 140); }
                  break;
               case 138:
                  if (curChar == 32)
                     { jjAddStates(76, 77); }
                  break;
               case 139:
                  if (curChar == 62 && kind > 15)
                     kind = 15;
                  break;
               case 141:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(141, 142); }
                  break;
               case 142:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(143, 147); }
                  break;
               case 143:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(143, 147); }
                  break;
               case 145:
                  if (curChar == 32)
                     { jjAddStates(78, 79); }
                  break;
               case 146:
                  if (curChar == 62 && kind > 16)
                     kind = 16;
                  break;
               case 148:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(148, 154); }
                  break;
               case 150:
                  if (curChar == 32)
                     { jjAddStates(80, 81); }
                  break;
               case 151:
                  if (curChar == 62 && kind > 17)
                     kind = 17;
                  break;
               case 155:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(155, 156); }
                  break;
               case 156:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(157, 163); }
                  break;
               case 157:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(157, 163); }
                  break;
               case 159:
                  if (curChar == 32)
                     { jjAddStates(82, 83); }
                  break;
               case 160:
                  if (curChar == 62 && kind > 18)
                     kind = 18;
                  break;
               case 164:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(164, 169); }
                  break;
               case 166:
                  if (curChar == 32)
                     { jjAddStates(84, 85); }
                  break;
               case 167:
                  if (curChar == 62 && kind > 19)
                     kind = 19;
                  break;
               case 170:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(170, 171); }
                  break;
               case 171:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(172, 177); }
                  break;
               case 172:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(172, 177); }
                  break;
               case 174:
                  if (curChar == 32)
                     { jjAddStates(86, 87); }
                  break;
               case 175:
                  if (curChar == 62 && kind > 20)
                     kind = 20;
                  break;
               case 178:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(178, 184); }
                  break;
               case 180:
                  if (curChar == 32)
                     { jjAddStates(88, 89); }
                  break;
               case 181:
                  if (curChar == 62 && kind > 21)
                     kind = 21;
                  break;
               case 185:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(185, 186); }
                  break;
               case 186:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(187, 193); }
                  break;
               case 187:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(187, 193); }
                  break;
               case 189:
                  if (curChar == 32)
                     { jjAddStates(90, 91); }
                  break;
               case 190:
                  if (curChar == 62 && kind > 22)
                     kind = 22;
                  break;
               case 194:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(194, 201); }
                  break;
               case 196:
                  if (curChar == 32)
                     { jjAddStates(92, 93); }
                  break;
               case 197:
                  if (curChar == 62 && kind > 23)
                     kind = 23;
                  break;
               case 202:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(202, 203); }
                  break;
               case 203:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(204, 211); }
                  break;
               case 204:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(204, 211); }
                  break;
               case 206:
                  if (curChar == 32)
                     { jjAddStates(94, 95); }
                  break;
               case 207:
                  if (curChar == 62 && kind > 24)
                     kind = 24;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  { jjCheckNAdd(1); }
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 27)
                     kind = 27;
                  { jjCheckNAdd(1); }
                  break;
               case 3:
                  { jjAddStates(96, 97); }
                  break;
               case 7:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(48, 49); }
                  break;
               case 10:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 11:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 15:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(50, 51); }
                  break;
               case 18:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 19:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 21:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(52, 53); }
                  break;
               case 24:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 25:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 32:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(54, 55); }
                  break;
               case 35:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 36:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 41:
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(56, 57); }
                  break;
               case 44:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 45:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 50:
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(58, 59); }
                  break;
               case 53:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 54:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 57:
                  if ((0x800000008000L & l) != 0L)
                     { jjAddStates(60, 61); }
                  break;
               case 60:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 61:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 66:
                  if ((0x800000008000L & l) != 0L)
                     { jjAddStates(62, 63); }
                  break;
               case 69:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 70:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 73:
                  if ((0x800000008000L & l) != 0L)
                     { jjAddStates(64, 65); }
                  break;
               case 76:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 77:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 84:
                  if ((0x800000008000L & l) != 0L)
                     { jjAddStates(66, 67); }
                  break;
               case 87:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 88:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 93:
                  if ((0x400000004000L & l) != 0L)
                     { jjAddStates(68, 69); }
                  break;
               case 96:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 97:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 98:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 104:
                  if ((0x400000004000L & l) != 0L)
                     { jjAddStates(70, 71); }
                  break;
               case 107:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 108:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 113:
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(72, 73); }
                  break;
               case 116:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 117:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 126:
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(74, 75); }
                  break;
               case 129:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 130:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 131:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 132:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 137:
                  if ((0x400000004L & l) != 0L)
                     { jjAddStates(76, 77); }
                  break;
               case 140:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 144:
                  if ((0x400000004L & l) != 0L)
                     { jjAddStates(78, 79); }
                  break;
               case 147:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 149:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(80, 81); }
                  break;
               case 152:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 153:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 158:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(82, 83); }
                  break;
               case 161:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 162:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 165:
                  if ((0x40000000400L & l) != 0L)
                     { jjAddStates(84, 85); }
                  break;
               case 168:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 169:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 168;
                  break;
               case 173:
                  if ((0x40000000400L & l) != 0L)
                     { jjAddStates(86, 87); }
                  break;
               case 176:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 177:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 179:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(88, 89); }
                  break;
               case 182:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 183:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 188:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(90, 91); }
                  break;
               case 191:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 188;
                  break;
               case 192:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 191;
                  break;
               case 193:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 195:
                  if ((0x200000002L & l) != 0L)
                     { jjAddStates(92, 93); }
                  break;
               case 198:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 199:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 200:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 205:
                  if ((0x200000002L & l) != 0L)
                     { jjAddStates(94, 95); }
                  break;
               case 208:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 209:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 3:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(96, 97); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 212 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   6, 11, 12, 13, 20, 28, 29, 30, 40, 46, 47, 48, 56, 62, 63, 64, 
   72, 80, 81, 82, 92, 100, 101, 102, 112, 122, 123, 124, 136, 140, 141, 142, 
   148, 154, 155, 156, 164, 169, 170, 171, 178, 184, 185, 186, 194, 201, 202, 203, 
   8, 9, 16, 17, 22, 23, 33, 34, 42, 43, 51, 52, 58, 59, 67, 68, 
   74, 75, 85, 86, 94, 95, 105, 106, 114, 115, 127, 128, 138, 139, 145, 146, 
   150, 151, 159, 160, 166, 167, 174, 175, 180, 181, 189, 190, 196, 197, 206, 207, 
   3, 4, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, "\61", 
"\60", null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public usrGrammarTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public usrGrammarTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 212; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x1fffffffL, 
};
static final long[] jjtoSkip = {
   0x1e0000000L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[212];
    private final int[] jjstateSet = new int[2 * 212];

    
    protected char curChar;
}
