/* funcGrammarTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. funcGrammarTokenManager.java */
package Analisis.XML.Funcion;
import Funciones.XML.*;
import Static.*;
import java.util.ArrayList;

/** Token Manager. */
@SuppressWarnings("unused")public class funcGrammarTokenManager implements funcGrammarConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1f800000L) != 0L)
         {
            jjmatchedKind = 33;
            return 7;
         }
         return -1;
      case 1:
         if ((active0 & 0x1f800000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 7;
         }
         return -1;
      case 2:
         if ((active0 & 0x1f800000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 7;
         }
         return -1;
      case 3:
         if ((active0 & 0x3000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 3;
            }
            return 7;
         }
         if ((active0 & 0x1c800000L) != 0L)
            return 7;
         return -1;
      case 4:
         if ((active0 & 0x13000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 7;
         }
         return -1;
      case 5:
         if ((active0 & 0x11000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
            return 7;
         }
         if ((active0 & 0x2000000L) != 0L)
            return 7;
         return -1;
      case 6:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 6;
            return 7;
         }
         if ((active0 & 0x1000000L) != 0L)
            return 7;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x4000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x1a000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x1000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x800000L);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x18000000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x6000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x19000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      case 69:
      case 101:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x11000000L);
      case 76:
      case 108:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 7);
         break;
      case 84:
      case 116:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(3, 23, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 7);
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000000L);
      case 82:
      case 114:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 24, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(7, 28, 7);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec1 = {
   0x0L, 0x0L, 0x8000000000L, 0x0L
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffff7fffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 221;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (curChar == 60)
                     { jjCheckNAddStates(0, 47); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 1:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 2:
                  if (curChar == 34 && kind > 29)
                     kind = 29;
                  break;
               case 4:
                  { jjAddStates(48, 49); }
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 8:
                  if (curChar == 60)
                     { jjCheckNAddStates(0, 47); }
                  break;
               case 9:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(9, 15); }
                  break;
               case 11:
                  if (curChar == 32)
                     { jjAddStates(50, 51); }
                  break;
               case 12:
                  if (curChar == 62 && kind > 1)
                     kind = 1;
                  break;
               case 16:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(16, 17); }
                  break;
               case 17:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(18, 24); }
                  break;
               case 18:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(18, 24); }
                  break;
               case 20:
                  if (curChar == 32)
                     { jjAddStates(52, 53); }
                  break;
               case 21:
                  if (curChar == 62 && kind > 2)
                     kind = 2;
                  break;
               case 25:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(25, 33); }
                  break;
               case 27:
                  if (curChar == 32)
                     { jjAddStates(54, 55); }
                  break;
               case 28:
                  if (curChar == 62 && kind > 3)
                     kind = 3;
                  break;
               case 34:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(34, 35); }
                  break;
               case 35:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(36, 44); }
                  break;
               case 36:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(36, 44); }
                  break;
               case 38:
                  if (curChar == 32)
                     { jjAddStates(56, 57); }
                  break;
               case 39:
                  if (curChar == 62 && kind > 4)
                     kind = 4;
                  break;
               case 45:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(45, 53); }
                  break;
               case 47:
                  if (curChar == 32)
                     { jjAddStates(58, 59); }
                  break;
               case 48:
                  if (curChar == 62 && kind > 5)
                     kind = 5;
                  break;
               case 54:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(54, 55); }
                  break;
               case 55:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(56, 64); }
                  break;
               case 56:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(56, 64); }
                  break;
               case 58:
                  if (curChar == 32)
                     { jjAddStates(60, 61); }
                  break;
               case 59:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 65:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(65, 71); }
                  break;
               case 67:
                  if (curChar == 32)
                     { jjAddStates(62, 63); }
                  break;
               case 68:
                  if (curChar == 62 && kind > 7)
                     kind = 7;
                  break;
               case 72:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(72, 73); }
                  break;
               case 73:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(74, 80); }
                  break;
               case 74:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(74, 80); }
                  break;
               case 76:
                  if (curChar == 32)
                     { jjAddStates(64, 65); }
                  break;
               case 77:
                  if (curChar == 62 && kind > 8)
                     kind = 8;
                  break;
               case 81:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(81, 86); }
                  break;
               case 83:
                  if (curChar == 32)
                     { jjAddStates(66, 67); }
                  break;
               case 84:
                  if (curChar == 62 && kind > 9)
                     kind = 9;
                  break;
               case 87:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(87, 88); }
                  break;
               case 88:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(89, 94); }
                  break;
               case 89:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(89, 94); }
                  break;
               case 91:
                  if (curChar == 32)
                     { jjAddStates(68, 69); }
                  break;
               case 92:
                  if (curChar == 62 && kind > 10)
                     kind = 10;
                  break;
               case 95:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(95, 101); }
                  break;
               case 97:
                  if (curChar == 32)
                     { jjAddStates(70, 71); }
                  break;
               case 98:
                  if (curChar == 62 && kind > 11)
                     kind = 11;
                  break;
               case 102:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(102, 111); }
                  break;
               case 104:
                  if (curChar == 32)
                     { jjAddStates(72, 73); }
                  break;
               case 105:
                  if (curChar == 62 && kind > 12)
                     kind = 12;
                  break;
               case 112:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(112, 120); }
                  break;
               case 114:
                  if (curChar == 32)
                     { jjAddStates(74, 75); }
                  break;
               case 115:
                  if (curChar == 62 && kind > 13)
                     kind = 13;
                  break;
               case 121:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(121, 127); }
                  break;
               case 123:
                  if (curChar == 32)
                     { jjAddStates(76, 77); }
                  break;
               case 124:
                  if (curChar == 62 && kind > 14)
                     kind = 14;
                  break;
               case 128:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(128, 134); }
                  break;
               case 130:
                  if (curChar == 32)
                     { jjAddStates(78, 79); }
                  break;
               case 131:
                  if (curChar == 62 && kind > 15)
                     kind = 15;
                  break;
               case 135:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(135, 145); }
                  break;
               case 137:
                  if (curChar == 32)
                     { jjAddStates(80, 81); }
                  break;
               case 138:
                  if (curChar == 62 && kind > 16)
                     kind = 16;
                  break;
               case 146:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(146, 147); }
                  break;
               case 147:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(148, 154); }
                  break;
               case 148:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(148, 154); }
                  break;
               case 150:
                  if (curChar == 32)
                     { jjAddStates(82, 83); }
                  break;
               case 151:
                  if (curChar == 62 && kind > 17)
                     kind = 17;
                  break;
               case 155:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(155, 156); }
                  break;
               case 156:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(157, 166); }
                  break;
               case 157:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(157, 166); }
                  break;
               case 159:
                  if (curChar == 32)
                     { jjAddStates(84, 85); }
                  break;
               case 160:
                  if (curChar == 62 && kind > 18)
                     kind = 18;
                  break;
               case 167:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(167, 168); }
                  break;
               case 168:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(169, 177); }
                  break;
               case 169:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(169, 177); }
                  break;
               case 171:
                  if (curChar == 32)
                     { jjAddStates(86, 87); }
                  break;
               case 172:
                  if (curChar == 62 && kind > 19)
                     kind = 19;
                  break;
               case 178:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(178, 179); }
                  break;
               case 179:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(180, 186); }
                  break;
               case 180:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(180, 186); }
                  break;
               case 182:
                  if (curChar == 32)
                     { jjAddStates(88, 89); }
                  break;
               case 183:
                  if (curChar == 62 && kind > 20)
                     kind = 20;
                  break;
               case 187:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(187, 188); }
                  break;
               case 188:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(189, 195); }
                  break;
               case 189:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(189, 195); }
                  break;
               case 191:
                  if (curChar == 32)
                     { jjAddStates(90, 91); }
                  break;
               case 192:
                  if (curChar == 62 && kind > 21)
                     kind = 21;
                  break;
               case 196:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(196, 197); }
                  break;
               case 197:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(198, 208); }
                  break;
               case 198:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(198, 208); }
                  break;
               case 200:
                  if (curChar == 32)
                     { jjAddStates(92, 93); }
                  break;
               case 201:
                  if (curChar == 62 && kind > 22)
                     kind = 22;
                  break;
               case 209:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(209, 210); }
                  break;
               case 211:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(94, 96); }
                  break;
               case 212:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(212, 213); }
                  break;
               case 213:
                  if (curChar == 62 && kind > 31)
                     kind = 31;
                  break;
               case 214:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(214, 215); }
                  break;
               case 215:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(216, 217); }
                  break;
               case 216:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(216, 217); }
                  break;
               case 218:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(97, 99); }
                  break;
               case 219:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(219, 220); }
                  break;
               case 220:
                  if (curChar == 62 && kind > 32)
                     kind = 32;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAdd(7); }
                  break;
               case 1:
                  { jjAddStates(100, 101); }
                  break;
               case 4:
                  { jjAddStates(48, 49); }
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  { jjCheckNAdd(7); }
                  break;
               case 10:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(50, 51); }
                  break;
               case 13:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 14:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 19:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(52, 53); }
                  break;
               case 22:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 23:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 26:
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(54, 55); }
                  break;
               case 29:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 30:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 31:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 33:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 37:
                  if ((0x8000000080000L & l) != 0L)
                     { jjAddStates(56, 57); }
                  break;
               case 40:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 41:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 42:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 43:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 46:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(58, 59); }
                  break;
               case 49:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 50:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 53:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 57:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(60, 61); }
                  break;
               case 60:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 61:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 62:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 63:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 66:
                  if ((0x800000008000L & l) != 0L)
                     { jjAddStates(62, 63); }
                  break;
               case 69:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 70:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 75:
                  if ((0x800000008000L & l) != 0L)
                     { jjAddStates(64, 65); }
                  break;
               case 78:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 79:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 80:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 82:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(66, 67); }
                  break;
               case 85:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 86:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 90:
                  if ((0x800000008L & l) != 0L)
                     { jjAddStates(68, 69); }
                  break;
               case 93:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 94:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 96:
                  if ((0x10000000100000L & l) != 0L)
                     { jjAddStates(70, 71); }
                  break;
               case 99:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 100:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 103:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(72, 73); }
                  break;
               case 106:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 107:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 108:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 113:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(74, 75); }
                  break;
               case 116:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 117:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 119:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 122:
                  if ((0x100000001000L & l) != 0L)
                     { jjAddStates(76, 77); }
                  break;
               case 125:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 126:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 127:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 129:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(78, 79); }
                  break;
               case 132:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 133:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 136:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(80, 81); }
                  break;
               case 139:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 136;
                  break;
               case 140:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 141:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               case 142:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 145:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 149:
                  if ((0x10000000100000L & l) != 0L)
                     { jjAddStates(82, 83); }
                  break;
               case 152:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 153:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 158:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(84, 85); }
                  break;
               case 161:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 162:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 170:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(86, 87); }
                  break;
               case 173:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 174:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 176:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 177:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 181:
                  if ((0x100000001000L & l) != 0L)
                     { jjAddStates(88, 89); }
                  break;
               case 184:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 185:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 190:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(90, 91); }
                  break;
               case 193:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 194:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 195:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 199:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(92, 93); }
                  break;
               case 202:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 203:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 205:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 207:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 210:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(94, 96); }
                  break;
               case 211:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(94, 96); }
                  break;
               case 217:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(97, 99); }
                  break;
               case 218:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(97, 99); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((jjbitVec1[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(4, 5); }
                  break;
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(100, 101); }
                  break;
               case 4:
                  if ((jjbitVec2[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(4, 5); }
                  break;
               case 5:
                  if ((jjbitVec1[i2] & l2) != 0L && kind > 30)
                     kind = 30;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 221 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   9, 15, 16, 17, 25, 33, 34, 35, 45, 53, 54, 55, 65, 71, 72, 73, 
   81, 86, 87, 88, 95, 101, 102, 111, 112, 120, 121, 127, 128, 134, 135, 145, 
   146, 147, 155, 156, 167, 168, 178, 179, 187, 188, 196, 197, 209, 210, 214, 215, 
   4, 5, 11, 12, 20, 21, 27, 28, 38, 39, 47, 48, 58, 59, 67, 68, 
   76, 77, 83, 84, 91, 92, 97, 98, 104, 105, 114, 115, 123, 124, 130, 131, 
   137, 138, 150, 151, 159, 160, 171, 172, 182, 183, 191, 192, 200, 201, 211, 212, 
   213, 218, 219, 220, 1, 2, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 1 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                              System.out.println(image);
         break;
      case 2 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                        System.out.println(image);
         break;
      case 3 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                   System.out.println(image);
         break;
      case 4 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                            System.out.println(image);
         break;
      case 5 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                   System.out.println(image);
         break;
      case 6 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                            System.out.println(image);
         break;
      case 7 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                               System.out.println(image);
         break;
      case 8 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                        System.out.println(image);
         break;
      case 9 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                             System.out.println(image);
         break;
      case 10 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                      System.out.println(image);
         break;
      case 11 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                              System.out.println(image);
         break;
      case 12 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                     System.out.println(image);
         break;
      case 13 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                   System.out.println(image);
         break;
      case 14 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                              System.out.println(image);
         break;
      case 15 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                               System.out.println(image);
         break;
      case 16 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                       System.out.println(image);
         break;
      case 17 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                        System.out.println(image);
         break;
      case 18 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                              System.out.println(image);
         break;
      case 19 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                            System.out.println(image);
         break;
      case 20 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                       System.out.println(image);
         break;
      case 21 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                        System.out.println(image);
         break;
      case 22 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                System.out.println(image);
         break;
      case 23 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 24 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                             System.out.println(image);
         break;
      case 25 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                           System.out.println(image);
         break;
      case 26 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 27 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                       System.out.println(image);
         break;
      case 28 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                               System.out.println(image);
         break;
      case 29 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                  System.out.println(image);
         break;
      case 30 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                            System.out.println(image);
         break;
      case 31 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                                      System.out.println(image);
         break;
      case 32 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                                               System.out.println(image);
         break;
      case 33 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                System.out.println(image);
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public funcGrammarTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public funcGrammarTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 221; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffffL, 
};
static final long[] jjtoSkip = {
   0x3c00000000L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[221];
    private final int[] jjstateSet = new int[2 * 221];

    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    
    protected char curChar;
}
