/* Generated By:JavaCC: Do not edit this line. procGrammarConstants.java */
package Analisis.XML.Procedimiento;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface procGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_PROC_IZQ = 1;
  /** RegularExpression Id. */
  int T_PROC_DER = 2;
  /** RegularExpression Id. */
  int T_PARAMS_IZQ = 3;
  /** RegularExpression Id. */
  int T_PARAMS_DER = 4;
  /** RegularExpression Id. */
  int T_NOMBRE_IZQ = 5;
  /** RegularExpression Id. */
  int T_NOMBRE_DER = 6;
  /** RegularExpression Id. */
  int T_SRC_IZQ = 7;
  /** RegularExpression Id. */
  int T_SRC_DER = 8;
  /** RegularExpression Id. */
  int T_TEXT_IZQ = 9;
  /** RegularExpression Id. */
  int T_INTEGER_IZQ = 10;
  /** RegularExpression Id. */
  int T_DOUBLE_IZQ = 11;
  /** RegularExpression Id. */
  int T_BOOL_IZQ = 12;
  /** RegularExpression Id. */
  int T_DATE_IZQ = 13;
  /** RegularExpression Id. */
  int T_DATETIME_IZQ = 14;
  /** RegularExpression Id. */
  int T_TEXT_DER = 15;
  /** RegularExpression Id. */
  int T_INTEGER_DER = 16;
  /** RegularExpression Id. */
  int T_DOUBLE_DER = 17;
  /** RegularExpression Id. */
  int T_BOOL_DER = 18;
  /** RegularExpression Id. */
  int T_DATE_DER = 19;
  /** RegularExpression Id. */
  int T_DATETIME_DER = 20;
  /** RegularExpression Id. */
  int CADENA = 21;
  /** RegularExpression Id. */
  int SRC = 22;
  /** RegularExpression Id. */
  int ID_IZQ = 23;
  /** RegularExpression Id. */
  int ID_DER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<T_PROC_IZQ>",
    "<T_PROC_DER>",
    "<T_PARAMS_IZQ>",
    "<T_PARAMS_DER>",
    "<T_NOMBRE_IZQ>",
    "<T_NOMBRE_DER>",
    "<T_SRC_IZQ>",
    "<T_SRC_DER>",
    "<T_TEXT_IZQ>",
    "<T_INTEGER_IZQ>",
    "<T_DOUBLE_IZQ>",
    "<T_BOOL_IZQ>",
    "<T_DATE_IZQ>",
    "<T_DATETIME_IZQ>",
    "<T_TEXT_DER>",
    "<T_INTEGER_DER>",
    "<T_DOUBLE_DER>",
    "<T_BOOL_DER>",
    "<T_DATE_DER>",
    "<T_DATETIME_DER>",
    "<CADENA>",
    "<SRC>",
    "<ID_IZQ>",
    "<ID_DER>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
