/* Generated By:JavaCC: Do not edit this line. tablaGrammarConstants.java */
package Analisis.XML.Tabla;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface tablaGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_ROW_IZQ = 1;
  /** RegularExpression Id. */
  int T_ROW_DER = 2;
  /** RegularExpression Id. */
  int CADENA = 3;
  /** RegularExpression Id. */
  int ID_IZQ = 4;
  /** RegularExpression Id. */
  int ID_DER = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<T_ROW_IZQ>",
    "<T_ROW_DER>",
    "<CADENA>",
    "<ID_IZQ>",
    "<ID_DER>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
