/* objGrammarTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. objGrammarTokenManager.java */
package Analisis.XML.Objeto;

/** Token Manager. */
@SuppressWarnings("unused")public class objGrammarTokenManager implements objGrammarConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 179;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if (curChar == 60)
                     { jjCheckNAddStates(0, 39); }
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(3, 8); }
                  break;
               case 5:
                  if (curChar == 32)
                     { jjAddStates(40, 41); }
                  break;
               case 6:
                  if (curChar == 62 && kind > 1)
                     kind = 1;
                  break;
               case 9:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(9, 10); }
                  break;
               case 10:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(11, 16); }
                  break;
               case 11:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(11, 16); }
                  break;
               case 13:
                  if (curChar == 32)
                     { jjAddStates(42, 43); }
                  break;
               case 14:
                  if (curChar == 62 && kind > 2)
                     kind = 2;
                  break;
               case 17:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(17, 23); }
                  break;
               case 19:
                  if (curChar == 32)
                     { jjAddStates(44, 45); }
                  break;
               case 20:
                  if (curChar == 62 && kind > 3)
                     kind = 3;
                  break;
               case 24:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(24, 25); }
                  break;
               case 25:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(26, 32); }
                  break;
               case 26:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(26, 32); }
                  break;
               case 28:
                  if (curChar == 32)
                     { jjAddStates(46, 47); }
                  break;
               case 29:
                  if (curChar == 62 && kind > 4)
                     kind = 4;
                  break;
               case 33:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(33, 41); }
                  break;
               case 35:
                  if (curChar == 32)
                     { jjAddStates(48, 49); }
                  break;
               case 36:
                  if (curChar == 62 && kind > 5)
                     kind = 5;
                  break;
               case 42:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(42, 43); }
                  break;
               case 43:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(44, 52); }
                  break;
               case 44:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(44, 52); }
                  break;
               case 46:
                  if (curChar == 32)
                     { jjAddStates(50, 51); }
                  break;
               case 47:
                  if (curChar == 62 && kind > 6)
                     kind = 6;
                  break;
               case 53:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(53, 59); }
                  break;
               case 55:
                  if (curChar == 32)
                     { jjAddStates(52, 53); }
                  break;
               case 56:
                  if (curChar == 62 && kind > 7)
                     kind = 7;
                  break;
               case 60:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(60, 69); }
                  break;
               case 62:
                  if (curChar == 32)
                     { jjAddStates(54, 55); }
                  break;
               case 63:
                  if (curChar == 62 && kind > 8)
                     kind = 8;
                  break;
               case 70:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(70, 78); }
                  break;
               case 72:
                  if (curChar == 32)
                     { jjAddStates(56, 57); }
                  break;
               case 73:
                  if (curChar == 62 && kind > 9)
                     kind = 9;
                  break;
               case 79:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(79, 85); }
                  break;
               case 81:
                  if (curChar == 32)
                     { jjAddStates(58, 59); }
                  break;
               case 82:
                  if (curChar == 62 && kind > 10)
                     kind = 10;
                  break;
               case 86:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(86, 92); }
                  break;
               case 88:
                  if (curChar == 32)
                     { jjAddStates(60, 61); }
                  break;
               case 89:
                  if (curChar == 62 && kind > 11)
                     kind = 11;
                  break;
               case 93:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(93, 103); }
                  break;
               case 95:
                  if (curChar == 32)
                     { jjAddStates(62, 63); }
                  break;
               case 96:
                  if (curChar == 62 && kind > 12)
                     kind = 12;
                  break;
               case 104:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(104, 105); }
                  break;
               case 105:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(106, 112); }
                  break;
               case 106:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(106, 112); }
                  break;
               case 108:
                  if (curChar == 32)
                     { jjAddStates(64, 65); }
                  break;
               case 109:
                  if (curChar == 62 && kind > 13)
                     kind = 13;
                  break;
               case 113:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(113, 114); }
                  break;
               case 114:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(115, 124); }
                  break;
               case 115:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(115, 124); }
                  break;
               case 117:
                  if (curChar == 32)
                     { jjAddStates(66, 67); }
                  break;
               case 118:
                  if (curChar == 62 && kind > 14)
                     kind = 14;
                  break;
               case 125:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(125, 126); }
                  break;
               case 126:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(127, 135); }
                  break;
               case 127:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(127, 135); }
                  break;
               case 129:
                  if (curChar == 32)
                     { jjAddStates(68, 69); }
                  break;
               case 130:
                  if (curChar == 62 && kind > 15)
                     kind = 15;
                  break;
               case 136:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(136, 137); }
                  break;
               case 137:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(138, 144); }
                  break;
               case 138:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(138, 144); }
                  break;
               case 140:
                  if (curChar == 32)
                     { jjAddStates(70, 71); }
                  break;
               case 141:
                  if (curChar == 62 && kind > 16)
                     kind = 16;
                  break;
               case 145:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(145, 146); }
                  break;
               case 146:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(147, 153); }
                  break;
               case 147:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(147, 153); }
                  break;
               case 149:
                  if (curChar == 32)
                     { jjAddStates(72, 73); }
                  break;
               case 150:
                  if (curChar == 62 && kind > 17)
                     kind = 17;
                  break;
               case 154:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(154, 155); }
                  break;
               case 155:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(156, 166); }
                  break;
               case 156:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(156, 166); }
                  break;
               case 158:
                  if (curChar == 32)
                     { jjAddStates(74, 75); }
                  break;
               case 159:
                  if (curChar == 62 && kind > 18)
                     kind = 18;
                  break;
               case 167:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(167, 168); }
                  break;
               case 169:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(76, 78); }
                  break;
               case 170:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(170, 171); }
                  break;
               case 171:
                  if (curChar == 62 && kind > 19)
                     kind = 19;
                  break;
               case 172:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(172, 173); }
                  break;
               case 173:
                  if (curChar == 47)
                     { jjCheckNAddTwoStates(174, 175); }
                  break;
               case 174:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(174, 175); }
                  break;
               case 176:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(79, 81); }
                  break;
               case 177:
                  if (curChar == 32)
                     { jjCheckNAddTwoStates(177, 178); }
                  break;
               case 178:
                  if (curChar == 62 && kind > 20)
                     kind = 20;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  { jjCheckNAdd(1); }
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  { jjCheckNAdd(1); }
                  break;
               case 4:
                  if ((0x40000000400L & l) != 0L)
                     { jjAddStates(40, 41); }
                  break;
               case 7:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 8:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 12:
                  if ((0x40000000400L & l) != 0L)
                     { jjAddStates(42, 43); }
                  break;
               case 15:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 16:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(44, 45); }
                  break;
               case 21:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 22:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 27:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(46, 47); }
                  break;
               case 30:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 31:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 34:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(48, 49); }
                  break;
               case 37:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 38:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 39:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 41:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 45:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(50, 51); }
                  break;
               case 48:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 49:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 51:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 52:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 54:
                  if ((0x10000000100000L & l) != 0L)
                     { jjAddStates(52, 53); }
                  break;
               case 57:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 58:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 61:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(54, 55); }
                  break;
               case 64:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 65:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 67:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 69:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 71:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(56, 57); }
                  break;
               case 74:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 75:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 78:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 80:
                  if ((0x100000001000L & l) != 0L)
                     { jjAddStates(58, 59); }
                  break;
               case 83:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 84:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 87:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(60, 61); }
                  break;
               case 90:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 91:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 94:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(62, 63); }
                  break;
               case 97:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 98:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 99:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 101;
                  break;
               case 103:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 107:
                  if ((0x10000000100000L & l) != 0L)
                     { jjAddStates(64, 65); }
                  break;
               case 110:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 111:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 116:
                  if ((0x4000000040000L & l) != 0L)
                     { jjAddStates(66, 67); }
                  break;
               case 119:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 120:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 121:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 122:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 123:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 128:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(68, 69); }
                  break;
               case 131:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 132:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 133:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 132;
                  break;
               case 134:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 135:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 139:
                  if ((0x100000001000L & l) != 0L)
                     { jjAddStates(70, 71); }
                  break;
               case 142:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 143:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 144:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 148:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(72, 73); }
                  break;
               case 151:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 152:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 151;
                  break;
               case 153:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 157:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(74, 75); }
                  break;
               case 160:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 161:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 162;
                  break;
               case 164:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 165:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 166:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 168:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(76, 78); }
                  break;
               case 169:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(76, 78); }
                  break;
               case 175:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(79, 81); }
                  break;
               case 176:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(79, 81); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 179 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   3, 8, 9, 10, 17, 23, 24, 25, 33, 41, 42, 43, 53, 59, 60, 69, 
   70, 78, 79, 85, 86, 92, 93, 103, 104, 105, 113, 114, 125, 126, 136, 137, 
   145, 146, 154, 155, 167, 168, 172, 173, 5, 6, 13, 14, 19, 20, 28, 29, 
   35, 36, 46, 47, 55, 56, 62, 63, 72, 73, 81, 82, 88, 89, 95, 96, 
   108, 109, 117, 118, 129, 130, 140, 141, 149, 150, 158, 159, 169, 170, 171, 176, 
   177, 178, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 1 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                            System.out.println(image);
         break;
      case 2 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                      System.out.println(image);
         break;
      case 3 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                               System.out.println(image);
         break;
      case 4 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                        System.out.println(image);
         break;
      case 5 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                   System.out.println(image);
         break;
      case 6 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                            System.out.println(image);
         break;
      case 7 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                              System.out.println(image);
         break;
      case 8 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                     System.out.println(image);
         break;
      case 9 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                   System.out.println(image);
         break;
      case 10 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                              System.out.println(image);
         break;
      case 11 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                               System.out.println(image);
         break;
      case 12 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                       System.out.println(image);
         break;
      case 13 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                        System.out.println(image);
         break;
      case 14 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                              System.out.println(image);
         break;
      case 15 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                            System.out.println(image);
         break;
      case 16 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                       System.out.println(image);
         break;
      case 17 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                        System.out.println(image);
         break;
      case 18 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                System.out.println(image);
         break;
      case 19 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                                      System.out.println(image);
         break;
      case 20 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                                               System.out.println(image);
         break;
      case 21 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                               System.out.println(image);
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public objGrammarTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public objGrammarTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 179; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3fffffL, 
};
static final long[] jjtoSkip = {
   0x3c00000L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[179];
    private final int[] jjstateSet = new int[2 * 179];

    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    
    protected char curChar;
}
