/* Generated By:JavaCC: Do not edit this line. objGrammarConstants.java */
package Analisis.XML.Objeto;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface objGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_OBJ_IZQ = 1;
  /** RegularExpression Id. */
  int T_OBJ_DER = 2;
  /** RegularExpression Id. */
  int T_ATTR_IZQ = 3;
  /** RegularExpression Id. */
  int T_ATTR_DER = 4;
  /** RegularExpression Id. */
  int T_NOMBRE_IZQ = 5;
  /** RegularExpression Id. */
  int T_NOMBRE_DER = 6;
  /** RegularExpression Id. */
  int T_TEXT_IZQ = 7;
  /** RegularExpression Id. */
  int T_INTEGER_IZQ = 8;
  /** RegularExpression Id. */
  int T_DOUBLE_IZQ = 9;
  /** RegularExpression Id. */
  int T_BOOL_IZQ = 10;
  /** RegularExpression Id. */
  int T_DATE_IZQ = 11;
  /** RegularExpression Id. */
  int T_DATETIME_IZQ = 12;
  /** RegularExpression Id. */
  int T_TEXT_DER = 13;
  /** RegularExpression Id. */
  int T_INTEGER_DER = 14;
  /** RegularExpression Id. */
  int T_DOUBLE_DER = 15;
  /** RegularExpression Id. */
  int T_BOOL_DER = 16;
  /** RegularExpression Id. */
  int T_DATE_DER = 17;
  /** RegularExpression Id. */
  int T_DATETIME_DER = 18;
  /** RegularExpression Id. */
  int ID_IZQ = 19;
  /** RegularExpression Id. */
  int ID_DER = 20;
  /** RegularExpression Id. */
  int ID = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<T_OBJ_IZQ>",
    "<T_OBJ_DER>",
    "<T_ATTR_IZQ>",
    "<T_ATTR_DER>",
    "<T_NOMBRE_IZQ>",
    "<T_NOMBRE_DER>",
    "<T_TEXT_IZQ>",
    "<T_INTEGER_IZQ>",
    "<T_DOUBLE_IZQ>",
    "<T_BOOL_IZQ>",
    "<T_DATE_IZQ>",
    "<T_DATETIME_IZQ>",
    "<T_TEXT_DER>",
    "<T_INTEGER_DER>",
    "<T_DOUBLE_DER>",
    "<T_BOOL_DER>",
    "<T_DATE_DER>",
    "<T_DATETIME_DER>",
    "<ID_IZQ>",
    "<ID_DER>",
    "<ID>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
