/* usqlGrammarTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. usqlGrammarTokenManager.java */
package Analisis.Usql;
import Funciones.Usql.*;
import Funciones.XML.*;
import Static.*;
import java.util.ArrayList;
import EjecucionUsql.*;

/** Token Manager. */
@SuppressWarnings("unused")public class usqlGrammarTokenManager implements usqlGrammarConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active0 & 0xffffffffc0000000L) != 0L || (active1 & 0x67fffffL) != 0L)
         {
            jjmatchedKind = 93;
            return 4;
         }
         return -1;
      case 1:
         if ((active1 & 0x49e9L) != 0L)
            return 4;
         if ((active0 & 0xffffffffc0000000L) != 0L || (active1 & 0x67fb616L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 1;
            }
            return 4;
         }
         return -1;
      case 2:
         if ((active1 & 0x4L) != 0L)
            return 4;
         if ((active0 & 0xfffffdffc0000000L) != 0L || (active1 & 0x67fff7aL) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 2;
            return 4;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 3:
         if ((active0 & 0x10008e40000000L) != 0L || (active1 & 0x1508L) != 0L)
            return 4;
         if ((active0 & 0xffeffd7180000000L) != 0L || (active1 & 0x67fea72L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 3;
            }
            return 4;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 4:
         if ((active0 & 0x2000015000000000L) != 0L || (active1 & 0x2030000L) != 0L)
            return 4;
         if ((active0 & 0xdfeffc2980000000L) != 0L || (active1 & 0x47cea72L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 4;
            }
            return 4;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 5:
         if ((active0 & 0x80200100000000L) != 0L || (active1 & 0x40000L) != 0L)
            return 4;
         if ((active0 & 0xdf6fdc2880000000L) != 0L || (active1 & 0x47aea72L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 5;
            return 4;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 6:
         if ((active0 & 0x967800080000000L) != 0L || (active1 & 0x4800L) != 0L)
            return 4;
         if ((active0 & 0x4000000000000000L) != 0L || (active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x96085c2800000000L) != 0L || (active1 & 0x462a272L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 6;
            return 4;
         }
         if ((active0 & 0x20000000000L) != 0L)
         {
            if (jjmatchedPos < 1)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 1;
            }
            return -1;
         }
         return -1;
      case 7:
         if ((active0 & 0x208000800000000L) != 0L || (active1 & 0xa040L) != 0L)
            return 4;
         if ((active1 & 0x32L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x4000000000000000L) != 0L || (active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x94005c2000000000L) != 0L || (active1 & 0x4620200L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 7;
            return 4;
         }
         return -1;
      case 8:
         if ((active1 & 0x4000000L) != 0L)
            return 4;
         if ((active1 & 0x32L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x4000000000000000L) != 0L || (active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x400000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 7;
            }
            return -1;
         }
         if ((active0 & 0x90005c2000000000L) != 0L || (active1 & 0x620200L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 8;
            return 4;
         }
         return -1;
      case 9:
         if ((active0 & 0x5c0000000000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 9;
            }
            return 4;
         }
         if ((active0 & 0x9000002000000000L) != 0L || (active1 & 0x20200L) != 0L)
            return 4;
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active1 & 0x32L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 10:
         if ((active0 & 0x8000000000000000L) != 0L)
            return 4;
         if ((active0 & 0x5c0000000000L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 10;
            return 4;
         }
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active1 & 0x32L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x400000000000000L) != 0L)
         {
            if (jjmatchedPos < 7)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 7;
            }
            return -1;
         }
         return -1;
      case 11:
         if ((active0 & 0x5c0000000000L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 11;
            return 4;
         }
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active1 & 0x30L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 12:
         if ((active0 & 0x500000000000L) != 0L)
            return 4;
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0xc0000000000L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 12;
            return 4;
         }
         if ((active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active1 & 0x30L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 13:
         if ((active0 & 0x80000000000L) != 0L)
            return 4;
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 13;
            return 4;
         }
         if ((active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active1 & 0x30L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         return -1;
      case 14:
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active1 & 0x180000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active1 & 0x30L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 14;
            return 4;
         }
         return -1;
      case 15:
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         if ((active1 & 0x30L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 15;
            return 4;
         }
         return -1;
      case 16:
         if ((active0 & 0x40000000000L) != 0L)
            return 4;
         if ((active1 & 0x600000L) != 0L)
         {
            if (jjmatchedPos < 8)
            {
               jjmatchedKind = 93;
               jjmatchedPos = 8;
            }
            return -1;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 29;
         return jjMoveStringLiteralDfa1_0(0x400000L, 0x0L);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x8000000L, 0x0L);
      case 40:
         return jjStopAtPos(0, 8);
      case 41:
         return jjStopAtPos(0, 9);
      case 42:
         return jjStopAtPos(0, 3);
      case 43:
         jjmatchedKind = 1;
         return jjMoveStringLiteralDfa1_0(0x40L, 0x0L);
      case 44:
         return jjStopAtPos(0, 15);
      case 45:
         jjmatchedKind = 2;
         return jjMoveStringLiteralDfa1_0(0x80L, 0x0L);
      case 46:
         return jjStopAtPos(0, 18);
      case 47:
         return jjStopAtPos(0, 4);
      case 58:
         return jjStopAtPos(0, 16);
      case 59:
         return jjStopAtPos(0, 14);
      case 60:
         jjmatchedKind = 23;
         return jjMoveStringLiteralDfa1_0(0x2080000L, 0x0L);
      case 61:
         jjmatchedKind = 17;
         return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L);
      case 62:
         jjmatchedKind = 24;
         return jjMoveStringLiteralDfa1_0(0x4100000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 12);
      case 93:
         return jjStopAtPos(0, 13);
      case 94:
         return jjStopAtPos(0, 5);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x1060040000000000L, 0x4L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x4000002200000000L, 0x180000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x104001000000000L, 0x40400L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x2000000d00000000L, 0x4869L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x200000000000000L, 0x0L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x2030000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x400000080000000L, 0x8000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x180000000000L, 0x0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x28000000000L, 0x0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x200000000000L, 0x12L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x8400000000000L, 0x1000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x600000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x380L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x4040000000L, 0x0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x12010000000000L, 0x0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0x4000000L);
      case 123:
         return jjStopAtPos(0, 10);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x10000000L, 0x0L);
      case 125:
         return jjStopAtPos(0, 11);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(1, 27);
         break;
      case 43:
         if ((active0 & 0x40L) != 0L)
            return jjStopAtPos(1, 6);
         break;
      case 45:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      case 60:
         if ((active0 & 0x80000L) != 0L)
            return jjStopAtPos(1, 19);
         break;
      case 61:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(1, 21);
         else if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(1, 22);
         else if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 25);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(1, 26);
         break;
      case 62:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(1, 20);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x908006c00000000L, active1, 0x2181400L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000000L, active1, 0L);
      case 69:
      case 101:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x8001000040000000L, active1, 0x4634a68L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L, active1, 0L);
      case 73:
      case 105:
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2100L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x220180000000000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x400010080000000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x6004020300000000L, active1, 0x40000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x401000000000L, active1, 0x2L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0x12000000000000L, active1, 0x4L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x80848000000000L, active1, 0L);
      case 124:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(1, 28);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L, active1, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x10180000000000L, active1, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000000L, active1, 0L);
      case 67:
      case 99:
         if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(2, 66, 4);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1b0040L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L, active1, 0x2000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x280010000000000L, active1, 0L);
      case 74:
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x8804008000000000L, active1, 0x2000200L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000800000000000L, active1, 0x40120L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x400200000000L, active1, 0x10L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x4040000000000000L, active1, 0x4001000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x408002000000000L, active1, 0x600408L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x1021040c80000000L, active1, 0x4000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000100000000L, active1, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 76, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x2001000000000L, active1, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000100000000L, active1, 0L);
      case 67:
      case 99:
         if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(3, 67, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0xc10000000000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000000000L, active1, 0x4000000L);
      case 69:
      case 101:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x8460202880000000L, active1, 0x4a22L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x30000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x180000L);
      case 76:
      case 108:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 33, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000L, active1, 0x40L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L, active1, 0x2000L);
      case 79:
      case 111:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 39, 4);
         else if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 72, 4);
         else if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 74, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x805040000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 52, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000000L, active1, 0x8010L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000000000L, active1, 0x2000000L);
      case 84:
      case 116:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 4);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000000L, active1, 0x640000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000000L, active1, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x180000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000L, active1, 0L);
      case 65:
      case 97:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 38, 4);
         else if ((active1 & 0x10000L) != 0L)
         {
            jjmatchedKind = 80;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x5080000000000000L, active1, 0x4660040L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x8004000000000000L, active1, 0xa00L);
      case 69:
      case 101:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 61, 4);
         return jjMoveStringLiteralDfa5_0(active0, 0x580000000000L, active1, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000080000000L, active1, 0x30L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x300840000000000L, active1, 0x8000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x4002L);
      case 79:
      case 111:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 40, 4);
         else if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(4, 89, 4);
         break;
      case 82:
      case 114:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 4);
         return jjMoveStringLiteralDfa5_0(active0, 0xc23000000000000L, active1, 0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x200800000000L, active1, 0x2000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L, active1, 0x180000L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active0, 0x180000000000L, active1, 0x20000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x164000000000000L, active1, 0x32L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000000000L, active1, 0x200L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x402000000000L, active1, 0x4000000L);
      case 69:
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 4);
         return jjMoveStringLiteralDfa6_0(active0, 0x800000080000000L, active1, 0x4000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000800000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000020000000000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x8000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x201040000000000L, active1, 0L);
      case 79:
      case 111:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 4);
         return jjMoveStringLiteralDfa6_0(active0, 0x8800000000000L, active1, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x180000L);
      case 82:
      case 114:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 55, 4);
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 82, 4);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000000L, active1, 0x2040L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000000000L, active1, 0x800L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x600000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(4, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1);
      return 6;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000000L, active1, 0x180000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x600002000000000L, active1, 0x2040L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x4000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L, active1, 0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x20000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x9000400000000000L, active1, 0x8200L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000000L, active1, 0L);
      case 78:
      case 110:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 47, 4);
         break;
      case 79:
      case 111:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(6, 41);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 48, 4);
         else if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 49, 4);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(6, 75, 4);
         break;
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000000L, active1, 0L);
      case 82:
      case 114:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 4);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 50, 4);
         else if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 53, 4);
         else if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 54, 4);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 4);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 78, 4);
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000L, active1, 0x600032L);
      case 83:
      case 115:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 59, 4);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(5, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1);
      return 7;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x32L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x600000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x100000L);
      case 68:
      case 100:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 51, 4);
         break;
      case 69:
      case 101:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(7, 35, 4);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000000000000L, active1, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000100000000000L, active1, 0x20200L);
      case 82:
      case 114:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 57, 4);
         else if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(7, 70, 4);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(7, 79, 4);
         return jjMoveStringLiteralDfa8_0(active0, 0x4000c0000000000L, active1, 0x4000000L);
      case 83:
      case 115:
         if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(7, 77, 4);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000L, active1, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x80000L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(6, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1);
      return 8;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000000000L, active1, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000000000L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000000000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x480000000000L, active1, 0L);
      case 78:
      case 110:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(8, 62);
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000000L, active1, 0x200L);
      case 79:
      case 111:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(8, 90, 4);
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000L, active1, 0x100000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x32L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000000L, active1, 0x620000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1);
      return 9;
   }
   switch(curChar)
   {
      case 32:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x600000L);
      case 65:
      case 97:
         if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 9;
         }
         else if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(9, 81, 4);
         return jjMoveStringLiteralDfa10_0(active0, 0x8000100000000000L, active1, 0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x400400000000000L, active1, 0x30L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa10_0(active0, 0xc0000000000L, active1, 0x100000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x2L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x80000L);
      case 82:
      case 114:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 60, 4);
         break;
      case 83:
      case 115:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 37, 4);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1);
      return 10;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000000000L, active1, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x400000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x80000L);
      case 78:
      case 110:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(10, 58);
         return jjMoveStringLiteralDfa11_0(active0, 0x500000000000L, active1, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x100000L);
      case 82:
      case 114:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 63, 4);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(10, 65);
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x30L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1);
      return 11;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x80000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x100000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x30L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000000L, active1, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x400000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000000000L, active1, 0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa12_0(active0, 0L, active1, 0x200000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa12_0(active0, 0x400000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, active1);
      return 12;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 44, 4);
         break;
      case 69:
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x100000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x80000000000L, active1, 0x30L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x400000L);
      case 79:
      case 111:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 46, 4);
         break;
      case 81:
      case 113:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x200000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa13_0(active0, 0x40000000000L, active1, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa13_0(active0, 0L, active1, 0x80000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, active1);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(11, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, active1);
      return 13;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 43, 4);
         return jjMoveStringLiteralDfa14_0(active0, 0x40000000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x200000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x80000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x400000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x30L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa14_0(active0, 0L, active1, 0x100000L);
      default :
         break;
   }
   return jjStartNfa_0(12, active0, active1);
}
private int jjMoveStringLiteralDfa14_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(12, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, active0, active1);
      return 14;
   }
   switch(curChar)
   {
      case 66:
      case 98:
         return jjMoveStringLiteralDfa15_0(active0, 0x40000000000L, active1, 0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa15_0(active0, 0L, active1, 0x200000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa15_0(active0, 0L, active1, 0x400000L);
      case 79:
      case 111:
         if ((active1 & 0x100000L) != 0L)
            return jjStopAtPos(14, 84);
         return jjMoveStringLiteralDfa15_0(active0, 0L, active1, 0x30L);
      case 80:
      case 112:
         if ((active1 & 0x80000L) != 0L)
            return jjStopAtPos(14, 83);
         break;
      default :
         break;
   }
   return jjStartNfa_0(13, active0, active1);
}
private int jjMoveStringLiteralDfa15_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(13, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, active0, active1);
      return 15;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa16_0(active0, 0L, active1, 0x400000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa16_0(active0, 0x40000000000L, active1, 0L);
      case 83:
      case 115:
         if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(15, 68);
         else if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(15, 69);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa16_0(active0, 0L, active1, 0x200000L);
      default :
         break;
   }
   return jjStartNfa_0(14, active0, active1);
}
private int jjMoveStringLiteralDfa16_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(14, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(15, active0, active1);
      return 16;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(16, 42, 4);
         break;
      case 77:
      case 109:
         return jjMoveStringLiteralDfa17_0(active0, 0L, active1, 0x200000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa17_0(active0, 0L, active1, 0x400000L);
      default :
         break;
   }
   return jjStartNfa_0(15, active0, active1);
}
private int jjMoveStringLiteralDfa17_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(15, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(16, 0L, active1);
      return 17;
   }
   switch(curChar)
   {
      case 79:
      case 111:
         if ((active1 & 0x400000L) != 0L)
            return jjStopAtPos(17, 86);
         break;
      case 80:
      case 112:
         if ((active1 & 0x200000L) != 0L)
            return jjStopAtPos(17, 85);
         break;
      default :
         break;
   }
   return jjStartNfa_0(16, 0L, active1);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 66;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 88)
                        kind = 88;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if (curChar == 39)
                     { jjAddStates(3, 8); }
                  else if (curChar == 35)
                  {
                     if (kind > 102)
                        kind = 102;
                     { jjCheckNAdd(14); }
                  }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(1, 2); }
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 1:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(1, 2); }
                  break;
               case 2:
                  if (curChar == 34 && kind > 87)
                     kind = 87;
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 93)
                     kind = 93;
                  jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 8:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(9, 11); }
                  break;
               case 9:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(9, 11); }
                  break;
               case 10:
                  if (curChar == 35 && kind > 101)
                     kind = 101;
                  break;
               case 11:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 13:
                  if (curChar != 35)
                     break;
                  if (kind > 102)
                     kind = 102;
                  { jjCheckNAdd(14); }
                  break;
               case 14:
                  if ((0xfffffffffffffbffL & l) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  { jjCheckNAdd(14); }
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 88)
                     kind = 88;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 88)
                     kind = 88;
                  { jjCheckNAdd(16); }
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(17, 18); }
                  break;
               case 18:
                  if (curChar == 46)
                     { jjCheckNAdd(19); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 92)
                     kind = 92;
                  { jjCheckNAdd(19); }
                  break;
               case 20:
                  if (curChar == 39)
                     { jjAddStates(3, 8); }
                  break;
               case 21:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 22:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 23:
                  if (curChar == 45)
                     { jjAddStates(9, 10); }
                  break;
               case 24:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 25:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(26); }
                  break;
               case 26:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if (curChar == 32)
                     { jjAddStates(11, 12); }
                  break;
               case 32:
                  if ((0x3000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(34); }
                  break;
               case 34:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x3f000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x3f000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if (curChar == 39 && kind > 95)
                     kind = 95;
                  break;
               case 41:
                  if (curChar == 50)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0xf000000000000L & l) != 0L)
                     { jjCheckNAdd(34); }
                  break;
               case 43:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 44:
                  if ((0x7000000000000L & l) != 0L)
                     { jjCheckNAdd(26); }
                  break;
               case 45:
                  if ((0x6000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 47:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x3000000000000L & l) != 0L)
                     { jjCheckNAdd(23); }
                  break;
               case 49:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(51); }
                  break;
               case 51:
                  if (curChar == 45)
                     { jjAddStates(13, 14); }
                  break;
               case 52:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x3fe000000000000L & l) != 0L)
                     { jjCheckNAdd(54); }
                  break;
               case 54:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if (curChar == 39 && kind > 96)
                     kind = 96;
                  break;
               case 60:
                  if (curChar == 49)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if ((0x7000000000000L & l) != 0L)
                     { jjCheckNAdd(54); }
                  break;
               case 62:
                  if ((0x6000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAdd(51); }
                  break;
               case 64:
                  if (curChar == 51)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x3000000000000L & l) != 0L)
                     { jjCheckNAdd(51); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 93)
                        kind = 93;
                     { jjCheckNAdd(4); }
                  }
                  else if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 1:
                  { jjAddStates(15, 16); }
                  break;
               case 3:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 93)
                     kind = 93;
                  { jjCheckNAdd(4); }
                  break;
               case 4:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 93)
                     kind = 93;
                  { jjCheckNAdd(4); }
                  break;
               case 5:
                  if (curChar == 64)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  { jjCheckNAdd(7); }
                  break;
               case 7:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  { jjCheckNAdd(7); }
                  break;
               case 9:
                  { jjAddStates(17, 18); }
                  break;
               case 14:
                  if (kind > 102)
                     kind = 102;
                  jjstateSet[jjnewStateCnt++] = 14;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(15, 16); }
                  break;
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(17, 18); }
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 102)
                     kind = 102;
                  jjstateSet[jjnewStateCnt++] = 14;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 66 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   16, 17, 18, 21, 45, 47, 49, 62, 64, 24, 43, 32, 41, 52, 60, 1, 
   2, 9, 11, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", "\53", "\55", "\52", "\57", "\136", "\53\53", "\55\55", "\50", "\51", 
"\173", "\175", "\133", "\135", "\73", "\54", "\72", "\75", "\56", "\74\74", "\76\76", 
"\75\75", "\41\75", "\74", "\76", "\74\75", "\76\75", "\46\46", "\174\174", "\41", null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
            SkipLexicalActions(matchedToken);
         }
         else
            SkipLexicalActions(null);
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 101 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                            System.out.println("multi" + image);
         break;
      case 102 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                        System.out.println("linea" + image);
         break;
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 1 :
        image.append(jjstrLiteralImages[1]);
        lengthOfMatch = jjstrLiteralImages[1].length();
               System.out.println(image);
         break;
      case 2 :
        image.append(jjstrLiteralImages[2]);
        lengthOfMatch = jjstrLiteralImages[2].length();
                  System.out.println(image);
         break;
      case 3 :
        image.append(jjstrLiteralImages[3]);
        lengthOfMatch = jjstrLiteralImages[3].length();
                System.out.println(image);
         break;
      case 4 :
        image.append(jjstrLiteralImages[4]);
        lengthOfMatch = jjstrLiteralImages[4].length();
                     System.out.println(image);
         break;
      case 5 :
        image.append(jjstrLiteralImages[5]);
        lengthOfMatch = jjstrLiteralImages[5].length();
                     System.out.println(image);
         break;
      case 6 :
        image.append(jjstrLiteralImages[6]);
        lengthOfMatch = jjstrLiteralImages[6].length();
                     System.out.println(image);
         break;
      case 7 :
        image.append(jjstrLiteralImages[7]);
        lengthOfMatch = jjstrLiteralImages[7].length();
                        System.out.println(image);
         break;
      case 8 :
        image.append(jjstrLiteralImages[8]);
        lengthOfMatch = jjstrLiteralImages[8].length();
                  System.out.println(image);
         break;
      case 9 :
        image.append(jjstrLiteralImages[9]);
        lengthOfMatch = jjstrLiteralImages[9].length();
                   System.out.println(image);
         break;
      case 10 :
        image.append(jjstrLiteralImages[10]);
        lengthOfMatch = jjstrLiteralImages[10].length();
                     System.out.println(image);
         break;
      case 11 :
        image.append(jjstrLiteralImages[11]);
        lengthOfMatch = jjstrLiteralImages[11].length();
                     System.out.println(image);
         break;
      case 12 :
        image.append(jjstrLiteralImages[12]);
        lengthOfMatch = jjstrLiteralImages[12].length();
                   System.out.println(image);
         break;
      case 13 :
        image.append(jjstrLiteralImages[13]);
        lengthOfMatch = jjstrLiteralImages[13].length();
                   System.out.println(image);
         break;
      case 14 :
        image.append(jjstrLiteralImages[14]);
        lengthOfMatch = jjstrLiteralImages[14].length();
                 System.out.println(image);
         break;
      case 15 :
        image.append(jjstrLiteralImages[15]);
        lengthOfMatch = jjstrLiteralImages[15].length();
                System.out.println(image);
         break;
      case 16 :
        image.append(jjstrLiteralImages[16]);
        lengthOfMatch = jjstrLiteralImages[16].length();
                System.out.println(image);
         break;
      case 17 :
        image.append(jjstrLiteralImages[17]);
        lengthOfMatch = jjstrLiteralImages[17].length();
                 System.out.println(image);
         break;
      case 18 :
        image.append(jjstrLiteralImages[18]);
        lengthOfMatch = jjstrLiteralImages[18].length();
                 System.out.println(image);
         break;
      case 19 :
        image.append(jjstrLiteralImages[19]);
        lengthOfMatch = jjstrLiteralImages[19].length();
                       System.out.println(image);
         break;
      case 20 :
        image.append(jjstrLiteralImages[20]);
        lengthOfMatch = jjstrLiteralImages[20].length();
                       System.out.println(image);
         break;
      case 21 :
        image.append(jjstrLiteralImages[21]);
        lengthOfMatch = jjstrLiteralImages[21].length();
                       System.out.println(image);
         break;
      case 22 :
        image.append(jjstrLiteralImages[22]);
        lengthOfMatch = jjstrLiteralImages[22].length();
                            System.out.println(image);
         break;
      case 23 :
        image.append(jjstrLiteralImages[23]);
        lengthOfMatch = jjstrLiteralImages[23].length();
                  System.out.println(image);
         break;
      case 24 :
        image.append(jjstrLiteralImages[24]);
        lengthOfMatch = jjstrLiteralImages[24].length();
                  System.out.println(image);
         break;
      case 25 :
        image.append(jjstrLiteralImages[25]);
        lengthOfMatch = jjstrLiteralImages[25].length();
                        System.out.println(image);
         break;
      case 26 :
        image.append(jjstrLiteralImages[26]);
        lengthOfMatch = jjstrLiteralImages[26].length();
                        System.out.println(image);
         break;
      case 27 :
        image.append(jjstrLiteralImages[27]);
        lengthOfMatch = jjstrLiteralImages[27].length();
                 System.out.println(image);
         break;
      case 28 :
        image.append(jjstrLiteralImages[28]);
        lengthOfMatch = jjstrLiteralImages[28].length();
                System.out.println(image);
         break;
      case 29 :
        image.append(jjstrLiteralImages[29]);
        lengthOfMatch = jjstrLiteralImages[29].length();
                System.out.println(image);
         break;
      case 30 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 31 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                             System.out.println(image);
         break;
      case 32 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                           System.out.println(image);
         break;
      case 33 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 34 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                       System.out.println(image);
         break;
      case 35 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                               System.out.println(image);
         break;
      case 36 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                         System.out.println(image);
         break;
      case 37 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                    System.out.println(image);
         break;
      case 38 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          System.out.println(image);
         break;
      case 39 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                        System.out.println(image);
         break;
      case 40 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          System.out.println(image);
         break;
      case 41 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 42 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                 System.out.println(image);
         break;
      case 43 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                            System.out.println(image);
         break;
      case 44 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                          System.out.println(image);
         break;
      case 45 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                            System.out.println(image);
         break;
      case 46 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                          System.out.println(image);
         break;
      case 47 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 48 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 49 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 50 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 51 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                System.out.println(image);
         break;
      case 52 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                        System.out.println(image);
         break;
      case 53 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 54 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 55 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                            System.out.println(image);
         break;
      case 56 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 57 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                System.out.println(image);
         break;
      case 58 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                   System.out.println(image);
         break;
      case 59 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 60 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                    System.out.println(image);
         break;
      case 61 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          System.out.println(image);
         break;
      case 62 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                               System.out.println(image);
         break;
      case 63 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                      System.out.println(image);
         break;
      case 64 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 65 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                  System.out.println(image);
         break;
      case 66 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 67 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                        System.out.println(image);
         break;
      case 68 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                       System.out.println(image);
         break;
      case 69 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                       System.out.println(image);
         break;
      case 70 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                  System.out.println(image);
         break;
      case 71 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 72 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          System.out.println(image);
         break;
      case 73 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                      System.out.println(image);
         break;
      case 74 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          System.out.println(image);
         break;
      case 75 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                System.out.println(image);
         break;
      case 76 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                          System.out.println(image);
         break;
      case 77 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                  System.out.println(image);
         break;
      case 78 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                System.out.println(image);
         break;
      case 79 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                  System.out.println(image);
         break;
      case 80 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                            System.out.println(image);
         break;
      case 81 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                      System.out.println(image);
         break;
      case 82 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 83 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                            System.out.println(image);
         break;
      case 84 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                System.out.println(image);
         break;
      case 85 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                  System.out.println(image);
         break;
      case 86 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                      System.out.println(image);
         break;
      case 87 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                  System.out.println(image);
         break;
      case 88 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 89 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                      System.out.println(image);
         break;
      case 90 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                              System.out.println(image);
         break;
      case 92 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                             System.out.println(image);
         break;
      case 93 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                System.out.println(image);
         break;
      case 94 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                      System.out.println(image);
         break;
      case 95 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                                                                                                                                                                                                          System.out.println(image + "hora");
         break;
      case 96 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                                                                                                       System.out.println( image + " fecha");
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public usqlGrammarTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public usqlGrammarTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 66; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffffffL, 0x1f7ffffffL, 
};
static final long[] jjtoSkip = {
   0x0L, 0x7e00000000L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x6000000000L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[66];
    private final int[] jjstateSet = new int[2 * 66];

    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    
    protected char curChar;
}
